# Generated by Django 4.1.5 on 2023-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_enrollment_price_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
