# Generated by Django 4.1.5 on 2023-01-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_trainer_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='SelectMembershipplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.membershipplan'),
        ),
    ]
