# Generated by Django 4.1.5 on 2023-01-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_enrollment_selectmembershipplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='SelectMembershipplan',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='MemberShipPlan',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
