# Generated by Django 4.1.5 on 2023-01-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_enrollment_selectmembershipplan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='MemberShipPlan',
            new_name='SelectMembershipplan',
        ),
    ]
